config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  #devise_for :admins
  get '/admin', to: 'admin/home#index'
  get '/home', to:'application#home'
  get '/show', to: 'application#show'
  get '/about', to: 'application#about'
  get '/contact', to: 'application#contact'
  get '/products', to: 'application#products'
  root 'application#home'
  namespace :admin do
    resources :categories
    resources :elements
    resources :brands
  end
  resources :elements, only:[:show,:index]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/element.rb
class Element < ApplicationRecord
  has_attached_file :image, styles: { medium: "270x300!", thumb: "100x100!" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  belongs_to :category, required: false
  belongs_to :brand
  searchkick


  def search_data
      {
        title: title,
        brand: brand
      }
  end



end

app/controllers/admin/elements_controller.rb
class Admin::ElementsController < Admin::ApplicationController
  before_action :set_element, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!
  layout 'admin'
  # GET /elements
  # GET /elements.json
  def index
    @elements = Element.all
  end

  # GET /elements/1
  # GET /elements/1.json
  def show
  end

  # GET /elements/new
  def new
    @element = Element.new
  end

  # GET /elements/1/edit
  def edit
  end

  def will_paginate
    @products = Element.paginate(:page => params[:page], :per_page => 30)
  end

  # POST /elements
  # POST /elements.json
  def create
    @element = Element.new(element_params)

    respond_to do |format|
      if @element.save
        format.html { redirect_to [:admin,@element], notice: 'Element was successfully created.' }
        format.json { render :show, status: :created, location: @element }
      else
        format.html { render :new }
        format.json { render json: @element.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /elements/1
  # PATCH/PUT /elements/1.json
  def update
    respond_to do |format|
      if @element.update(element_params)
        format.html { redirect_to [:admin, @element], notice: 'Element was successfully updated.' }
        format.json { render :show, status: :ok, location: @element }
      else
        format.html { render :edit }
        format.json { render json: @element.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /elements/1
  # DELETE /elements/1.json
  def destroy
    @element.destroy
    respond_to do |format|
      format.html { redirect_to admin_elements_url, notice: 'Element was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_element
      @element = Element.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def element_params
      params.require(:element).permit(:title, :description, :image, :price, :brand_id)
    end
end

app/controllers/elements_controller.rb
class ElementsController < ApplicationController
  before_action :set_element, only: [:show]


  def show

  end

  def set_element
    @element = Element.find(params[:id])
  end

  def index
    @found = Element.search(params['search'], fields: [:title, :brand])
  end


end

app/helpers/element_helper.rb
module ElementHelper
end

app/helpers/elements_helper.rb
module ElementsHelper
end

app/views/elements/index.html.erb
<br>


        <!-- Start page content -->
        <div id="page-content" class="page-wrapper">

            <!-- SHOP SECTION START -->
            <div class="shop-section mb-80">
                <div class="container">
                    <div class="row">
                        <div class="col-md-9 col-md-push-3 col-sm-12">
                            <div class="shop-content">
                                <!-- shop-option start -->
                                <div class="shop-option box-shadow mb-30 clearfix">
                                    <!-- Nav tabs -->
                                    <ul class="shop-tab f-left" role="tablist">
                                        <li class="active">
                                            <a href="#grid-view" data-toggle="tab"><i class="zmdi zmdi-view-module"></i></a>
                                        </li>
                                        <li>
                                            <a href="#list-view" data-toggle="tab"><i class="zmdi zmdi-view-list-alt"></i></a>
                                        </li>
                                    </ul>
                                    <!-- short-by -->
                                    <!-- <div class="short-by f-left text-center">
                                        <span>Filtrar por:</span>
                                        <select>
                                          <option value="mercedes">Lo mas nuevo</option>
                                          <option value="audi">Lo mas antiguo</option>
                                          <option value="volvo">Precio mas bajo</option>
                                          <option value="saab">Precio mas alto</option>
                                        </select>
                                    </div> -->
                                    <!-- showing -->
                                    <div class="showing f-right text-right">
                                        <span> Total productos: <%= @elements.count %></span>
                                    </div>
                                </div>
                                <!-- shop-option end -->
                                <!-- Tab Content start -->
                                <div class="tab-content">
                                    <!-- grid-view -->

                                    <div role="tabpanel" class="tab-pane active" id="grid-view">
                                      <% @found.each do |element| %>
                                        <div class="col-md-3 col-sm-4 col-xs-12">
                                            <div class="product-item">
                                                <div class="product-img">
                                                    <%=link_to (image_tag element.image.url(:medium)), element_path(element) %>

                                                    </a>
                                                </div>
                                                <div class="product-info">
                                                    <h6 class="product-title">
                                                        <%=link_to element.title, element_path(element) %>
                                                    </h6>

                                                    <h3 class="pro-price">$<%= element.price %></h3>

                                                </div>
                                            </div>
                                        </div>
                                      <% end %>
                                    </div>
                                    <!-- list-view -->
                                    <div role="tabpanel" class="tab-pane" id="list-view">
                                        <div class="row">
                                            <!-- product-item start -->
                                            <% @elements.sort_by{|t| - t.created_at.to_i}.each do |element| %>
                                            <div class="col-md-12">
                                                <div class="shop-list product-item">
                                                    <div class="product-img">
                                                        <a href="single-product.html">
                                                            <%=link_to (image_tag element.image.url(:medium)), element_path(element) %>
                                                        </a>
                                                    </div>
                                                    <div class="product-info">
                                                        <div class="clearfix">
                                                            <h6 class="product-title f-left">
                                                                <%=link_to element.title, element_path(element) %>
                                                            </h6>
                                                        </div>
                                                        <h6 class="brand-name mb-30">Brand Name</h6>
                                                        <h3 class="pro-price">$ <%= element.price%> </h3>
                                                        <p><%= element.description %><p>
                                                    </div>
                                                </div>
                                            </div>
                                            <% end %>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3 col-md-pull-9 col-sm-12">
                            <!-- widget-search -->
                            <aside class="widget-search mb-30">
                              <%= form_tag elements_path, method: :get do %>
                                    <input name="search" type="text" placeholder="Busque aquí...">
                                    <button type="submit"><i class="zmdi zmdi-search"></i></button>
                              <% end %>
                            </aside>
                            <!-- widget-categories -->
                            <aside class="widget widget-categories box-shadow mb-30">
                                <h6 class="widget-title border-left mb-20">Categorias</h6>
                                <div id="cat-treeview" class="product-cat">
                                    <% @categories.each do |category| %>
                                    <ul>
                                      <li class="open"><%=link_to category.title, products_path %>
                                            <% category.categories.each do |category2| %>
                                            <ul>
                                              <li><%= link_to category2.title, products_path%> </li>
                                            </ul>
                                            <% end %>
                                        </li>
                                    </ul>
                                    <% end %>
                                </div>
                            </aside>

                        </div>
                    </div>
                </div>
            </div>
            <!-- SHOP SECTION END -->
            <!-- Tab Content end -->

        </div>
        <!-- End page content -->
        <!-- shop-pagination start -->
        <ul class="shop-pagination box-shadow text-center ptblr-10-30">
        <%= will_paginate @elements %>
        </ul>
        <!-- shop-pagination end -->
    </div>
    <!-- Body main wrapper end -->


    <!-- Placed JS at the end of the document so the pages load faster -->

    <!-- jquery latest version -->