config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  #devise_for :admins
  get '/admin', to: 'admin/home#index'
  get '/home', to:'application#home'
  get '/show', to: 'application#show'
  get '/about', to: 'application#about'
  get '/contact', to: 'application#contact'
  get '/products', to: 'application#products'
  root 'application#home'
  namespace :admin do
    resources :categories
    resources :elements
    resources :brands
  end
  resources :elements, only:[:show,:index]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :elements
end

app/controllers/admin/brands_controller.rb
class Admin::BrandsController < Admin::ApplicationController
  before_action :set_brand, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!
  layout 'admin'
  # GET /brands
  # GET /brands.json
  def index
    @brands = Brand.all
  end

  # GET /brands/1
  # GET /brands/1.json
  def show
  end

  # GET /brands/new
  def new
    @brand = Brand.new
  end

  # GET /brands/1/edit
  def edit
  end

  # POST /brands
  # POST /brands.json
  def create
    @brand = Brand.new(brand_params)

    respond_to do |format|
      if @brand.save
        format.html { redirect_to [:admin, @brand], notice: 'Brand was successfully created.' }
        format.json { render :show, status: :created, location: @brand }
      else
        format.html { render :new }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /brands/1
  # PATCH/PUT /brands/1.json
  def update
    respond_to do |format|
      if @brand.update(brand_params)
        format.html { redirect_to [:admin,@brand], notice: 'Brand was successfully updated.' }
        format.json { render :show, status: :ok, location: @brand }
      else
        format.html { render :edit }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brands/1
  # DELETE /brands/1.json
  def destroy
    @brand.destroy
    respond_to do |format|
      format.html { redirect_to admin_brands_url, notice: 'Brand was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brand
      @brand = Brand.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def brand_params
      params.require(:brand).permit(:name)
    end
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  before_action :set_element, only: [:show]


  def show

  end

  def set_brand
    @brand = Brand.find(params[:id])
  end
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/views/admin/brands/_form.html.erb
<%= form_for [:admin, @brand], :html => { :class => "form-horizontal brand" } do |f| %>

  <% if @brand.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@brand.errors.count, "error") %> prohibited this brand from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @brand.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                admin_brands_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/admin/brands/edit.html.erb
<%- model_class = Brand -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/admin/brands/index.html.erb
<%- model_class = Brand -%>
<div class="page-header">
  <h1><%=t 'marcas' %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:nombre) %></th>
      <th><%= model_class.human_attribute_name(:fecha_de_creacion) %></th>
      <th><%=t '.actions', :default => t("acciones") %></th>
    </tr>
  </thead>
  <tbody>
    <% @brands.each do |brand| %>
      <tr>
        <td><%= link_to brand.id, admin_brand_path(brand) %></td>
        <td><%= brand.name %></td>
        <td><%= brand.created_at.strftime("%d %b %Y") %></td>
        <td>
          <%= link_to t('.show', :default => t("ver")),
                      admin_brand_path(brand), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("editar")),
                      edit_admin_brand_path(brand), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("eliminar")),
                      admin_brand_path(brand),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_admin_brand_path,
            :class => 'btn btn-primary' %>

app/views/admin/brands/new.html.erb
<%- model_class = Brand -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/admin/brands/show.html.erb
<%- model_class = Brand -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @brand.name %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              admin_brands_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_admin_brand_path(@brand), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              admin_brand_path(@brand),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>