config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  #devise_for :admins
  get '/admin', to: 'admin/home#index'
  get '/home', to:'application#home'
  get '/show', to: 'application#show'
  get '/about', to: 'application#about'
  get '/contact', to: 'application#contact'
  get '/products', to: 'application#products'
  root 'application#home'
  namespace :admin do
    resources :categories
    resources :elements
    resources :brands
  end
  resources :elements, only:[:show,:index]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/element.rb
class Element < ApplicationRecord
  has_attached_file :image, styles: { medium: "270x300!", thumb: "100x100!" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  belongs_to :category, required: false
  belongs_to :brand
  searchkick


  def search_data
      {
        title: title,
        brand: brand
      }
  end



end

app/controllers/admin/elements_controller.rb
class Admin::ElementsController < Admin::ApplicationController
  before_action :set_element, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!
  layout 'admin'
  # GET /elements
  # GET /elements.json
  def index
    @elements = Element.all
  end

  # GET /elements/1
  # GET /elements/1.json
  def show
  end

  # GET /elements/new
  def new
    @element = Element.new
  end

  # GET /elements/1/edit
  def edit
  end

  def will_paginate
    @products = Element.paginate(:page => params[:page], :per_page => 30)
  end

  # POST /elements
  # POST /elements.json
  def create
    @element = Element.new(element_params)

    respond_to do |format|
      if @element.save
        format.html { redirect_to [:admin,@element], notice: 'Element was successfully created.' }
        format.json { render :show, status: :created, location: @element }
      else
        format.html { render :new }
        format.json { render json: @element.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /elements/1
  # PATCH/PUT /elements/1.json
  def update
    respond_to do |format|
      if @element.update(element_params)
        format.html { redirect_to [:admin, @element], notice: 'Element was successfully updated.' }
        format.json { render :show, status: :ok, location: @element }
      else
        format.html { render :edit }
        format.json { render json: @element.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /elements/1
  # DELETE /elements/1.json
  def destroy
    @element.destroy
    respond_to do |format|
      format.html { redirect_to admin_elements_url, notice: 'Element was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_element
      @element = Element.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def element_params
      params.require(:element).permit(:title, :description, :image, :price, :brand_id)
    end
end

app/controllers/elements_controller.rb
class ElementsController < ApplicationController
  before_action :set_element, only: [:show]


  def show

  end

  def set_element
    @element = Element.find(params[:id])
  end

  def index
    @found = Element.search(params['search'], fields: [:title, :brand])
  end


end

app/helpers/element_helper.rb
module ElementHelper
end

app/helpers/elements_helper.rb
module ElementsHelper
end

app/views/admin/elements/_form.html.erb
<%= form_for [:admin, @element], :html => { :class => "form-horizontal element" } do |f| %>

  <% if @element.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@element.errors.count, "error") %> prohibited this element from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @element.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :title, :class => 'form-control', :required => true %>
    </div>
    <%=f.error_span(:title) %>
  </div>


  <div class="form-group">
    <%= f.label :description, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :description, :class => 'form-control', :required => true %>
    </div>
    <%=f.error_span(:description) %>
  </div>

  <div class="form-group">
    <%= f.label :brand_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.select :brand_id, options_for_select(Brand.all.map{|b| [b.name, b.id]}, @element.brand_id), {prompt: "Seleccione una marca"}, :class => 'form-control' %>
    </div>
    <%=f.error_span(:brand) %>
  </div>


  <div class="form-group">
    <%= f.label :price, :class => 'control-label col-lg-2' %>
    <div class="col-lg-2">
      <%= f.number_field :price, :class => 'form-control', :required => true %>
    </div>
    <%=f.error_span(:price) %>
  </div>

  <div class="form-group">
    <%= f.label :image, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.file_field :image, :class => 'form-control', :required => true %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :category_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.select :category_id, options_for_select(Category.all.map{|c| [c.title, c.id]}, @element.category_id), {}, :class => 'form-control' %>
    </div>
    <%=f.error_span(:category) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                admin_elements_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/admin/elements/edit.html.erb
<%- model_class = Element -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/admin/elements/index.html.erb
<%- model_class = Element -%>
<div class="page-header">
  <h1><%=t 'Productos' %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:nombre) %></th>
      <th><%= model_class.human_attribute_name(:descripcion) %></th>
      <th><%= model_class.human_attribute_name(:imagen) %></th>
      <th><%= model_class.human_attribute_name(:fecha_creación) %></th>
      <th><%=t '.actions', :default => t("acciones") %></th>
    </tr>
  </thead>
  <tbody>
    <% @elements.each do |element| %>
      <tr>
        <td><%= link_to element.id, admin_element_path(element) %></td>
        <td><%= element.title %></td>
        <td><%= element.description %></td>
        <td><%= image_tag(element.image.url(:thumb)) %></td>
        <td><%= element.created_at.strftime("%d %b %Y") %></td>
        <td>
          <%= link_to t('.show', :default => t("ver")),
                      admin_element_path(element), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("editar")),
                      edit_admin_element_path(element), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("eliminar")),
                      admin_element_path(element),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_admin_element_path,
            :class => 'btn btn-primary' %>

app/views/admin/elements/new.html.erb
<%- model_class = Element -%>
<div class="page-header">
  <h1><%=t 'Nuevo producto'%></h1>
</div>
<%= render :partial => 'form' %>

app/views/admin/elements/show.html.erb
<%- model_class = Element -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @element.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @element.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:image_file_name) %>:</strong></dt>
  <dd><%= @element.image_file_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:image_content_type) %>:</strong></dt>
  <dd><%= @element.image_content_type %></dd>
  <dt><strong><%= model_class.human_attribute_name(:image_file_size) %>:</strong></dt>
  <dd><%= @element.image_file_size %></dd>
  <dt><strong><%= model_class.human_attribute_name(:image_updated_at) %>:</strong></dt>
  <dd><%= @element.image_updated_at %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              admin_elements_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_admin_element_path(@element), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              admin_element_path(@element),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>