config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  #devise_for :admins
  get '/admin', to: 'admin/home#index'
  get '/home', to:'application#home'
  get '/show', to: 'application#show'
  get '/about', to: 'application#about'
  get '/contact', to: 'application#contact'
  get '/products', to: 'application#products'
  root 'application#home'
  namespace :admin do
    resources :categories
    resources :elements
    resources :brands
  end
  resources :elements, only:[:show,:index]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Acondiparts" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/admin">Acondiparts|Admin</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Categorias", admin_categories_path  %></li>
            <li><%= link_to "Productos", admin_elements_path  %></li>
            <li><%= link_to "Marcas", admin_brands_path  %></li>
            <li><%= link_to "Cerrar sesion", destroy_admin_session_path, method: :delete  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>


      <footer>

      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/layouts/application.html.erb
<!doctype html>
<html class="no-js" lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Acondiparts || Catalogo online</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Favicon -->
    <link rel="shortcut icon" type="image/x-icon" href="/img/icon/favicon.png">

    <!-- All CSS Files -->
    <!-- Bootstrap fremwork main css -->
    <link rel="stylesheet" href="/css/bootstrap.min.css">
    <!-- Nivo-slider css -->
    <link rel="stylesheet" href="/lib/css/nivo-slider.css">
    <!-- This core.css file contents all plugings css file. -->
    <link rel="stylesheet" href="/css/core.css">
    <!-- Theme shortcodes/elements style -->
    <link rel="stylesheet" href="/css/shortcode/shortcodes.css">
    <!-- Theme main style -->
    <link rel="stylesheet" href="/css/style.css">
    <!-- Responsive css -->
    <link rel="stylesheet" href="/css/responsive.css">
    <!-- Template color css -->
    <link href="/css/color/color-core.css" data-style="styles" rel="stylesheet">
    <!-- User style -->
    <link rel="stylesheet" href="/css/custom.css">
    
    <%= javascript_include_tag "application" %>


    <!-- Modernizr JS -->
    <script src="/js/vendor/modernizr-2.8.3.min.js"></script>
</head>

<body class="boxed-layout">
    <!--[if lt IE 8]>
        <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->

    <!-- Body main wrapper start -->
    <div class="wrapper">

        <!-- START HEADER AREA -->
        <header class="header-area header-wrapper">
            <!-- header-top-bar -->
            <div class="header-top-bar plr-185">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-sm-6 hidden-xs">
                            <div class="call-us">
                                <p class="mb-0 roboto">FONO: (2)27620341</p>
                            </div>
                        </div>
                        <div class="col-sm-6 col-xs-12">
                            <div class="top-link clearfix">
                                <ul class="link f-right">
                                    <li>
                                        <a href="/admin">
                                            <i class="zmdi zmdi-lock"></i>
                                            Login
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- header-middle-area -->
            <div id="sticky-header" class="header-middle-area plr-185">
                <div class="container-fluid">
                    <div class="full-width-mega-dropdown">
                        <div class="row">
                            <!-- logo -->
                            <div class="col-md-2 col-sm-6 col-xs-12">
                                <div class="logo">
                                    <a href="/home">
                                        <img src="/img/logo/logo.png" alt="main logo" height="100%" width="100%">
                                    </a>
                                </div>
                            </div>
                            <!-- primary-menu -->
                            <div class="col-md-8 hidden-sm hidden-xs">
                                <nav id="primary-menu">
                                    <ul class="main-menu text-center">
                                        <li><%= link_to "Inicio", root_path%></li>
                                        <li class="mega-parent"><%= link_to "Productos", products_path%>
                                            <div class="mega-menu-area clearfix">
                                                <div class="mega-menu-link mega-menu-link-4  f-left">
                                                    <% @categories.each do |category| %>
                                                    <ul class="single-mega-item">
                                                      <!-- Aqui se debera usar un each por categoria -->
                                                        <li class="menu-title"><%= category.title %></li>
                                                        <% category.categories.each do |category2| %>

                                                        <li>
                                                          <%= link_to category2.title , products_path %>
                                                        </li><% end %>
                                                    </ul><% end %>
                                                </div>
                                            </div>
                                        </li>

                                        <li>
                                          <%= link_to "Sobre nosotros", about_path%>

                                        </li>
                                        <li>
                                          <%= link_to "Contacto", contact_path%>
                                        </li>
                                    </ul>
                                </nav>
                            </div>
                            <!-- header-search & total-cart -->
                            <div class="col-md-2 col-sm-6 col-xs-12">
                                <div class="search-top-cart  f-right">
                                    <!-- header-search -->
                                    <div class="header-search f-left">
                                        <div class="header-search-inner">
                                           <button class="search-toggle">
                                            <i class="zmdi zmdi-search"></i>
                                           </button>
                                            <%= form_tag elements_path, method: :get do %>
                                                <div class="top-search-box">
                                                    <input name="search" type="text" placeholder="Busque aquí su producto...">
                                                    <button type="submit">
                                                        <i class="zmdi zmdi-search"></i>
                                                    </button>
                                                </div>
                                            <% end %>
                                        </div>
                                    </div>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- END HEADER AREA -->

        <!-- START MOBILE MENU AREA -->
        <div class="mobile-menu-area hidden-lg hidden-md">
            <div class="container">
                <div class="row">
                    <div class="col-xs-12">
                        <div class="mobile-menu">
                            <nav id="dropdown">
                                  <ul>
                                    <li><%= link_to "Inicio", root_path%></li>
                                    <li>
                                        <%= link_to "Productos", products_path%>
                                        <ul>
                                        <% @categories.each do |category| %>
                                          <li>
                                            <%= link_to category.title, products_path %>
                                            <% category.categories.each do |category2| %>
                                            <ul>
                                            <li><%= link_to category2.title , products_path %></li>
                                          </li></ul><% end %>
                                    </li><% end %>
                                  </ul>
                                    <li><%= link_to "Sobre nosotros", about_path%></li>

                                    <li><%= link_to "Contacto", contact_path%></li>
                                </ul>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- END MOBILE MENU AREA -->


        <!-- Start page content -->
        <%= yield %>
        <!-- End page content -->

        <!-- START FOOTER AREA -->
        <footer id="footer" class="footer-area">
            <div class="footer-top">
                <div class="container-fluid">
                    <div class="plr-185">
                        <div class="footer-top-inner gray-bg">
                            <div class="row">
                                <div class="col-lg-4 col-md-5 col-sm-4">
                                    <div class="single-footer footer-about">
                                        <div class="footer-logo">
                                            <img src="img/logo/logo.png" alt="" height="120%" width="120">
                                        </div>
                                        <div class="footer-brief">
                                            <b>Dirección: </b>
                                            <br>
                                            <p>Euclides #1425, San Miguel, Santiago</p>
                                            <b>Email: </b>
                                            <p>ventas@acondiparts.cl</p>
                                            <b>Fono: </b>
                                            <p>(2)27620341</p>
                                        </div>
                                        <ul class="footer-social">
                                            <li>
                                                <a class="facebook" href="https://www.facebook.com/acondiparts.daikin.5" target="_blank" title="Facebook"><i class="zmdi zmdi-facebook"></i></a>
                                            </li>
                                            <!-- <li>
                                                <a class="google-plus" href="" title="Google Plus"><i class="zmdi zmdi-google-plus"></i></a>
                                            </li>
                                            <li>
                                                <a class="twitter" href="" title="Twitter"><i class="zmdi zmdi-twitter"></i></a>
                                            </li>
                                            <li>
                                                <a class="rss" href="" title="RSS"><i class="zmdi zmdi-rss"></i></a>
                                            </li> -->
                                        </ul>
                                    </div>
                                </div>

                                <div class="col-lg-2 col-md-3 col-sm-4">
                                    <div class="single-footer">
                                        <h4 class="footer-title border-left">Links</h4>
                                        <!-- Falta establecer que va aqui -->
                                        <ul class="footer-menu">
                                            <li>
                                              <%= link_to "Panel administrador", admin_path %>
                                            </li>
                                            <li>
                                              <%= link_to "Web mail", 'https://blue59.dnsmisitio.net:2096' %>
                                            </li>
                                        </ul>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="footer-bottom black-bg">
                <div class="container-fluid">
                    <div class="plr-185">
                        <div class="copyright">
                            <div class="row">
                                <div class="col-sm-6 col-xs-12">
                                    <div class="copyright-text">
                                        <p>&copy; <a href="https://themeforest.net/user/codecarnival/portfolio" target="_blank">CodeCarnival</a> 2016. All Rights Reserved.</p>
                                    </div>
                                </div>
                              </div>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- END FOOTER AREA -->

        <!-- START QUICKVIEW PRODUCT -->

        <!-- END QUICKVIEW PRODUCT -->
    </div>
    <!-- Body main wrapper end -->


    <!-- Placed JS at the end of the document so the pages load faster -->

    <!-- jquery latest version -->
    <script src="/js/vendor/jquery-3.1.1.min.js"></script>
    <!-- Bootstrap framework js -->
    <script src="/js/bootstrap.min.js"></script>
    <!-- jquery.nivo.slider js -->
    <script src="/lib/js/jquery.nivo.slider.js"></script>
    <!-- All js plugins included in this file. -->
    <script src="/js/plugins.js"></script>
    <!-- Main js file that contents all jQuery plugins activation. -->
    <script src="/js/main.js"></script>

</body>

</html>